CREATE TABLE "GCG_4018_BIN"(
 "PART" CHAR(20),
 "DESCRIPTION" CHAR(30),
  "BIN" CHAR(6),
  "BIN_DESCRIPTION" CHAR(30),
 "UM_INVENTORY" CHAR(3),
 "QTY_ONHAND" NUMERIC(12,4),
 "CODE_ABC" CHAR(1),
 "DATE_CYCLE" CHAR(6),
 "CYCLE_DATE_START" CHAR(6),
 "CYCLE_DATE_END" CHAR(6),
 "BIRUNID" BIGINT 
 );